remote_theme: jekyll/minima

title: 神户小鸟的秘密营地
author:
  name: Kanbe Kotori
  email: kotori@nulladev.cn
  
description: >
  如你所见，这里基本只是个堆积各种随笔和吐槽文的地方。

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"
  
header_pages:
 - index.md
# - travels/index.md
 - about/index.md
  
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme